### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by Beliavsky** [marshallward/flint#7]
Could you provide installation instructions?

**Comment by marshallward** [comment]
Beyond what's in the README, I'm not sure there is too much that I can say here.  It can be used, but I would not call it "usable" :).  That is, even I sometimes cannot remember how I managed to use it.

The best I can suggest:

* Check out the repository into some directory
* Copy one of the scripts out of the `tools` directory (currently configured for my own projects) into the repo directory
* Replace the directories in the tool script with paths to your own source
* Run the scripts inside the repo directory

You will get something.  But I can't promise it will be anything useful.

This project is a very long way from ready, but thanks for having a look.

**Comment by marshallward** [comment]
I've added a very simple setup.py script if you want to have a go with it.
```
python setup.py install
```
or if you want to sandbox it a bit:
```
python -m venv env
source env/bin/activate
python setup.py install
```

There is really only one command at the moment, `gendoc` which can generate reStructuredText documentation from the docstrings (Doxygen style at the moment).  Otherwise, the module can be loaded and one can experiment with some of the example snippets in the README.

Again, I would not expect much at this stage.

**Comment by marshallward** [comment]
I've updated the README to include the setup.py install instructions.

Development has been moving quickly lately, to the point where the basic infrastructure is all working now, and `flint report` does something meaningful (albeit just cosmetic stuff like trailing whitespace).  So I think it's OK to close this issue now.
